name: 🐛 Bug Report
description: Report a bug or issue with the website
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what actually happened
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop
        - Tablet
        - Mobile (iPhone)
        - Mobile (Android)
        - Other
    validations:
      required: true

  - type: input
    id: screen-size
    attributes:
      label: Screen Size
      description: What is your screen resolution or viewport size?
      placeholder: e.g., 1920x1080 or 375px width

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console? (F12 → Console tab)
      placeholder: Paste console errors here
      render: shell

  - type: input
    id: url
    attributes:
      label: URL
      description: What page were you on when you encountered this bug?
      placeholder: https://yellowflowersorganicfarm.com/articles/...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How severe is this bug?
      options:
        - 🔴 Critical (site broken/unusable)
        - 🟠 High (major feature broken)
        - 🟡 Medium (minor issue, workaround exists)
        - 🟢 Low (cosmetic issue)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

