name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Another way to solve this would be...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Article/Content
        - New Website Section
        - UI/UX Improvement
        - Performance Enhancement
        - Accessibility Improvement
        - New Functionality
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔴 Critical (blocking important workflows)
        - 🟠 High (significantly improves experience)
        - 🟡 Medium (nice to have)
        - 🟢 Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who will benefit from this feature and how?
      placeholder: |
        - Visitors will be able to...
        - Farmers will find it easier to...
        - This will improve...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, sketches, or examples from other sites
      placeholder: Drag and drop images or provide links

  - type: dropdown
    id: willing-to-implement
    attributes:
      label: Implementation
      description: Are you willing to implement this feature?
      options:
        - ✅ Yes, I can implement this
        - ⚠️ I can help, but need guidance
        - ❌ No, I'm just suggesting
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request

